# Permissions
# ================
# Player Commands:
# sLottery.buy
# sLottery.claim
# sLottery.info
# sLottery.list
# sLottery.winners
# Admin Commands:
# sLottery.create
# sLottery.draw
# sLottery.reload
# VaultLottery-Specific Permissions:
# sLottery.LotteryName - base permission
# sLottery.{LotteryName}.limit.bypass - bypass ticket limit
# sLottery.{LotteryName}.buy - allows purchasing tickets
# sLottery.{LotteryName}.warnings - receive reminders
# sLottery.{LotteryName}.joinmsg - reminders on join

#in minutes
save-interval: 5
msg-prefix: "&2[sLottery] "
no-permission: "{RED}No permissions to perform this action."

lotteries:
  LottoLotto:
    type: "VaultLottery"
    #if not set, use parent name (LottoLotto)
    display-name: '&4LottoLotto'
    enabled: true
    allow-purchases: true
    automatic: true
    #in hours
    time: 24
    starting-pot: 20
    ticket-cost: 1000
    total-ticket-limit: 300
    player-ticket-limit: 10
    warnings:
      - 12h
      - 6h
      - 3h
      - 1h
      - 30m
      - 15m
      - 10m
      - 5m
      - 1m
     #WorldGuard - if not set, it will allow everywhere
    remind: true
    allowed-regions:
      - gamblerlair
  EliteLotto:
    type: "VaultLottery"
    enabled: true
    allow-purchases: true
    automatic: true
    #in hours
    time: 48
    starting-pot: 1000
    ticket-cost: 20000
    total-ticket-limit: 30
    player-ticket-limit: 3
    warnings:
      - 12h
      - 6h
      - 3h
      - 1h
      - 30m
      - 15m
      - 10m
      - 5m
      - 1m
    remind: true
    allowed-regions:
      - gamblerlair